### PR TITLE
Add an alternative AWS provider for the DNS validation

### PR DESCRIPTION
**Pull request by dboesswetter**
In my current project I need to request certificates for a zone which lives in a different account. To let this module do the validation with this zone, I needed to use an alternative AWS provider which assumes a role in the account that contains the zone. This small change should be backward compatible and will add a way to do this.

Let me know what you think.

### CODE REVIEW

**Comment by Gowiem** [comment]
@dboesswetter I don't know if we would want to roll this into the main line as it seems like a one off fix that you might be able to fix outside of the module since your use-case is so specific. I wonder, would it suffice for you if you set `local.process_domain_validation_options` to false for you local usage and then do the DNS validation outside of the module?

Happy to chat through this!

**Comment by Gowiem** [comment]
@osterman @aknysh What do you gents think of this type of PR? 

I was thinking of creating something similar to this for cloudposse/terraform-aws-route53-cluster-zone as I need it for a client, but instead of including a provider alias directly like @dboesswetter did here I was thinking adding an `_enabled` flag that allows disabling external account resources might be a better approach. Then the module consumer can disable any resources that are in an external account and create those resources in their consuming project instead. 

How has CP done this type of cross account resource handling and what do you folks prefer? The module.providers approach or flagged + consumer handles multiple providers approach?

**Comment by Gowiem** [comment]
@dboesswetter I discussed with @osterman about this and the Cloud Posse view is to not introduce the additional complexity of accepting provider aliases. I suggest going the route of disabling the resources you wanted to create with an aliased provider and create them after usage of this module in your root module. If you need any additional changes to this module to support that use-case then put them up on PR and assign me and we can work to get those changes merged quickly. Thanks for the effort and sorry we couldn't get this merged!

**Comment by osterman** [comment]
In the cloudposse model, we have two types of domains: branded/vanity domains, and service discovery domains. Service discovery domains delegate zones to each account so each account shares nothing. Then we have the concept of primary and delegated zones. For vanity domains, one account is designated the primary, typically a prod account. We strictly do not do cross account DNS by design. Understand this is opinionated and doesn't fit the bill for everyone, especially existing environments. The problem with introducing a second provider is we cannot mark it optional. And while this is technically easy to overcome by passing the same provider twice, this would be the first time in any of our modules (other than for VPC peering). Hope that helps clear up our position.

**Comment by dboesswetter** [comment]
@osterman @Gowiem Thanks for the clarification. I see your point and fortunately my problem could be solved in a different way.

**Pull request closed without merging**
