### PR TITLE
add the option for certificate_transparency_logging_preference

### PR DESCRIPTION
**Pull request by marcelobartsch**
## what
* Add the option to DISABLE or ENABLE certificate_transparency_logging_preference parameter when creating the certificate

## why
* Some cases you don't want to disclose certificate names, as also this may leak internal information when you use this module for internal domains ACM generation in a split horizon dns configuration.

### CODE REVIEW

**Comment by mihaiplesa** [comment]
@marcelobartsch it would be really nice to have this in.

**Comment by marcelobartsch** [comment]
I totally miss this message 5 month ago, will fix now!

**Comment by nitrocode** [comment]
Looks like it's failing due to the data source finding more than one zone.

> Error: multiple Route53Zone found please use vpc_id option to filter

This does not seem related to the PR but this needs to be resolved in order to complete the tests. I messaged the team but no eta currently.

**Comment by marcelobartsch** [comment]
> Looks like it's failing due to the data source finding more than one zone.
> 
> > Error: multiple Route53Zone found please use vpc_id option to filter
> 
> This does not seem related to the PR but this needs to be resolved in order to complete the tests. I messaged the team but no eta currently.

This can be also related to multiple domains in the test environment with the same name :/ I added a small change to the examples/complete

**Comment by marcelobartsch** [comment]
looks like the random_string breaks more things than fixes

**Comment by marcelobartsch** [comment]
sorry for the huge number of commits on this PR :( but trying to solve the issue related with the test has been a PITA :(

**Comment by marcelobartsch** [comment]
If it fails, is OK to scream and cry like a baby? :)

**Comment by Gowiem** [comment]
@marcelobartsch I do that all the time, so yeah totally okay 😉

**Review by Gowiem — APPROVED** [review]

**Comment by Gowiem** [comment]
Well done @marcelobartsch, the terratest gods were looking down kindly on you today 💯 👍 

Released as [0.14.0](https://github.com/cloudposse/terraform-aws-acm-request-certificate/releases/tag/0.14.0)

**Pull request merged**
