### PR TITLE
remove uneeded tolist as is set now

### PR DESCRIPTION
**Pull request by pjaudiomv**
## what
there is no need to convert to a list anymore as its a set

## why

fixes bug introduced by me :)

## references
* issue from slack thread https://sweetops.slack.com/archives/CB6GHNLG0/p1609784495001600

### CODE REVIEW

**Review by jamengual — DISMISSED** [review]

**Comment by pjaudiomv** [comment]
ok empty set doesn't work with for_each ref https://github.com/hashicorp/terraform/issues/23970 to fix im explicitly using toset on empty list

**Comment by pjaudiomv** [comment]
OK I assure you this is no longer a WIP :)

**Review by jamengual — APPROVED** [review]

**Pull request merged**
