### PR TITLE
Ensure domain names & SANs are lower-case

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
If you provide an upper-case domain name, this module fails with the following error:

  on .terraform/modules/my_certificate/main.tf line 37, in resource "aws_route53_record" "default":
  37:   name            = each.value.name
A reference to "each.value" has been used in a context in which it
unavailable, such as when the configuration no longer contains the value in
its "for_each" expression. Remove this reference to each.value in your
configuration to work around this error.

## what
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.

## why
* Provide the justifications for the changes (e.g. business case). 
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.

## references
* Link to any supporting github issues or helpful documentation to add some context (e.g. stackoverflow). 
* Use `closes #123`, if this PR closes a GitHub issue `#123`

### CODE REVIEW

**Comment by Gowiem** [comment]
@alexjurkiewicz mind fixing the merge conflicts and we'll get this merged? Seems valid and I'm sure we can bump the minimum version of tf for this module at this point.

**Comment by alexjurkiewicz** [comment]
> @alexjurkiewicz mind fixing the merge conflicts and we'll get this merged? Seems valid and I'm sure we can bump the minimum version of tf for this module at this point.

done 🙏

**Review by Gowiem — DISMISSED** [review]

**Comment by Gowiem** [comment]
@alexjurkiewicz 💥 

```
TestExamplesComplete 2021-07-14T19:13:53Z command.go:121: 
TestExamplesComplete 2021-07-14T19:13:53Z command.go:121: Error: Invalid value for variable
TestExamplesComplete 2021-07-14T19:13:53Z command.go:121: 
TestExamplesComplete 2021-07-14T19:13:53Z command.go:121:   on main.tf line 19, in module "acm_request_certificate":
TestExamplesComplete 2021-07-14T19:13:53Z command.go:121:   19:   subject_alternative_names         = ["*.${module.zone.zone_name}"]
TestExamplesComplete 2021-07-14T19:13:53Z command.go:121: 
TestExamplesComplete 2021-07-14T19:13:53Z command.go:121: All SANs must be lower-case.
TestExamplesComplete 2021-07-14T19:13:53Z command.go:121: 
TestExamplesComplete 2021-07-14T19:13:53Z command.go:121: This was checked by the validation rule at ../../variables.tf:40,3-13.
TestExamplesComplete 2021-07-14T19:13:53Z command.go:121: 
TestExamplesComplete 2021-07-14T19:13:53Z command.go:121: 
TestExamplesComplete 2021-07-14T19:13:53Z command.go:121: Error: no matching Route53Zone found
TestExamplesComplete 2021-07-14T19:13:53Z command.go:121: 
TestExamplesComplete 2021-07-14T19:13:53Z command.go:121:   on ../../main.tf line 22, in data "aws_route53_zone" "default":
TestExamplesComplete 2021-07-14T19:13:53Z command.go:121:   22: data "aws_route53_zone" "default" {
TestExamplesComplete 2021-07-14T19:13:53Z command.go:121: 
TestExamplesComplete 2021-07-14T19:13:53Z command.go:121: 
TestExamplesComplete 2021-07-14T19:13:53Z retry.go:80: Returning due to fatal error: FatalError{Underlying: exit status 1}
    require.go:794: 
        	Error Trace:	apply.go:14
        	            				examples_complete_test.go:26
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: exit status 1}
        	Test:       	TestExamplesComplete
```

**Comment by alexjurkiewicz** [comment]
Whoops, inverted condition, pushed a fix

**Comment by Gowiem** [comment]
Huh we're getting the following: 

```
TestExamplesComplete 2021-08-04T19:39:25Z command.go:121: module.zone.data.template_file.zone_name[0]: Refreshing state...
TestExamplesComplete 2021-08-04T19:39:28Z command.go:121: 
TestExamplesComplete 2021-08-04T19:39:28Z command.go:121: Error: no matching Route53Zone found
TestExamplesComplete 2021-08-04T19:39:28Z command.go:121: 
TestExamplesComplete 2021-08-04T19:39:28Z command.go:121:   on ../../main.tf line 22, in data "aws_route53_zone" "default":
TestExamplesComplete 2021-08-04T19:39:28Z command.go:121:   22: data "aws_route53_zone" "default" {
TestExamplesComplete 2021-08-04T19:39:28Z command.go:121: 
TestExamplesComplete 2021-08-04T19:39:28Z command.go:121: 
TestExamplesComplete 2021-08-04T19:39:28Z retry.go:80: Returning due to fatal error: FatalError{Underlying: exit status 1}
    require.go:794: 
        	Error Trace:	apply.go:14
        	            				examples_complete_test.go:26
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: exit status 1}
        	Test:       	TestExamplesComplete
```

I don't have time to look into now, but possibly a problem with the test suite overall?

**Comment by alexjurkiewicz** [comment]
I can't see how it's related to this PR, at least.

**Comment by nitrocode** [comment]
@Gowiem @alexjurkiewicz This PR will fix the test https://github.com/cloudposse/terraform-aws-acm-request-certificate/pull/48

**Pull request closed without merging**
