### PR TITLE
readme: typo in example

### PR DESCRIPTION
**Pull request by philwinder**
Minor typo in readme. Should say proces**S**.

### CODE REVIEW

**Comment by aknysh** [comment]
@philwinder thanks

please update it in README.yaml and then rebuild README.md by executing:

```
make init
make readme/deps
make readme
```

**Comment by osterman** [comment]
Also, come join our slack team! We're getting all of our awesome contributors together so we can collaborate efficiently =)

https://slack.cloudposse.com

**Comment by aknysh** [comment]
@philwinder let's finish this :)
please see the comment above.
thanks

**Comment by philwinder** [comment]
@aknysh There you go. Sorry, didn't realise the docs were generated from the yaml. Thanks!

**Pull request merged**
