### PR TITLE
Fix dns validation processing

### LINKED ISSUE #30: Issue when creating certificate with wildcards
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[Slack Community](https://slack.cloudposse.com)

## Describe the Bug
The below causes an `invalid index` error (see screenshots section for output)

```hcl
module "acm_internal" {
  source  = "cloudposse/acm-request-certificate/aws"
  version = "0.8.0"

  domain_name                       = "*.internal.example_com"
  zone_name                         = aws_route53_zone.example_com.name
  subject_alternative_names = [
    "*.example_com"
  ]

  process_domain_validation_options = true
  ttl                               = "60"

  tags = module.tagging.tags
}
```

## Expected Behavior
Having wildcards in the domain_name and subject_alternative_names is valid; it should not cause the issue above. 

## Steps to Reproduce
Plan and apply the given example. 

## Screenshots
```consoleError: Invalid index

  on .terraform/modules/acm_internal/main.tf line 30, in resource "aws_route53_record" "default":
  30:   name            = lookup(local.domain_validation_options_list[count.index], "resource_record_name")
    |----------------
    | count.index is 0
    | local.domain_validation_options_list is set of object with 2 elements

This value does not have any indices.


Error: Invalid index

  on .terraform/modules/acm_internal/main.tf line 30, in resource "aws_route53_record" "default":
  30:   name            = lookup(local.domain_validation_options_list[count.index], "resource_record_name")
    |----------------
    | count.index is 1
    | local.domain_validation_options_list is set of object with 2 elements

This value does not have any indices.


Error: Invalid index

  on .terraform/modules/acm_internal/main.tf line 31, in resource "aws_route53_record" "default":
  31:   type            = lookup(local.domain_validation_options_list[count.index], "resource_record_type")
    |----------------
    | count.index is 0
    | local.domain_validation_options_list is set of object with 2 elements

This value does not have any indices.


Error: Invalid index

  on .terraform/modules/acm_internal/main.tf line 31, in resource "aws_route53_record" "default":
  31:   type            = lookup(local.domain_validation_options_list[count.index], "resource_record_type")
    |----------------
    | count.index is 1
    | local.domain_validation_options_list is set of object with 2 elements

This value does not have any indices.


Error: Invalid index

  on .terraform/modules/acm_internal/main.tf line 32, in resource "aws_route53_record" "default":
  32:   records         = [lookup(local.domain_validation_options_list[count.index], "resource_record_value")]
    |----------------
    | count.index is 0
    | local.domain_validation_options_list is set of object with 2 elements

This value does not have any indices.


Error: Invalid index

  on .terraform/modules/acm_internal/main.tf line 32, in resource "aws_route53_record" "default":
  32:   records         = [lookup(local.domain_validation_options_list[count.index], "resource_record_value")]
    |----------------
    | count.index is 1
    | local.domain_validation_options_list is set of object with 2 elements


```

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: Linux
 - Version 0.13.4
 - Terraform AWS provider 3.11.0

### PR DESCRIPTION
**Pull request by dlundgren**
## what
Certificates with wildcards cause invalid processing.

## why
Allow the DNS processing to work with wildcard certificates

## references
Fixes #30

### CODE REVIEW

**Comment by dlundgren** [comment]
I took a look at the error and it's occurring for Terraform 0.12, I've tried multiple work arounds, but I can't get it to actually work without hitting the deterministic error.

I'm currently using Terraform 0.13, and my fork of the repo with these changes is working fine.

There are several changes to `examples/complete` for Terraform 0.13 to work, I can attach them to this PR if desired.

**Comment by dlundgren** [comment]
I reverted back to the `length(var.subject_alternative_names) + 1` and tested that this is working in TF 0.12.29, and 0.13.5.

**Review by aknysh — APPROVED** [review]

**Pull request merged**
