### PR TITLE
Add ability to specify key_algorithm closes #69

### LINKED ISSUE #69: Add ability to specify key_algorithm for certs setup with this module
### Describe the Feature

As described in this blog post (https://aws.amazon.com/blogs/security/how-to-evaluate-and-use-ecdsa-certificates-in-aws-certificate-manager/), it is now possible to issue ECDSA certs using ACM. And the underlying Terraform module (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate) supports the `key_algorithm` option that lets us set that. However this module doesn't currently allow passing that value in

### Expected Behavior

I'd expect to be able to pass `key_algorithm=EC_prime256v1` and see the appropriate cert generated in ACM

### Use Case

ECDSA certs use less bandwidth and computation power to work. They're starting to be used more heavily in IoT deploys as described in the above blog post

### Describe Ideal Solution

We'd add a new option to this module

### Alternatives Considered

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by joke**
## what

add ability to specify key algorithm.

## why

to specify key algorithm

## references

#69

### CODE REVIEW

**Comment by gberenice** [comment]
@joke thanks for contributing to this!
Could you please fix a couple of things to make the checks happy:
1. Update README file:
   * Run `make init` (you only need to do this once)
   * Run `make readme` to rebuild this file.
2. Address lint error:
```
Warning: [Fixable] List items should be accessed using square brackets (terraform_deprecated_index)

  on main.tf line 4:
   4:   domain_validation_options_set     = local.process_domain_validation_options ? aws_acm_certificate.default.0.domain_validation_options : toset([])

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.5.0/docs/rules/terraform_deprecated_index.md

Warning: [Fixable] List items should be accessed using square brackets (terraform_deprecated_index)

  on main.tf line 63:
  63:   certificate_arn         = join("", aws_acm_certificate.default.*.arn)

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.5.0/docs/rules/terraform_deprecated_index.md

Warning: [Fixable] List items should be accessed using square brackets (terraform_deprecated_index)

  on outputs.tf line 2:
   2:   value       = join("", aws_acm_certificate.default.*.id)

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.5.0/docs/rules/terraform_deprecated_index.md

Warning: [Fixable] List items should be accessed using square brackets (terraform_deprecated_index)

  on outputs.tf line 7:
   7:   value       = join("", aws_acm_certificate.default.*.arn)

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.5.0/docs/rules/terraform_deprecated_index.md

Warning: [Fixable] List items should be accessed using square brackets (terraform_deprecated_index)

  on outputs.tf line 12:
  12:   value       = aws_acm_certificate.default.*.domain_validation_options

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.5.0/docs/rules/terraform_deprecated_index.md

Warning: [Fixable] List items should be accessed using square brackets (terraform_deprecated_index)

  on outputs.tf line 17:
  17:   value       = join("", aws_acm_certificate_validation.default.*.id)

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.5.0/docs/rules/terraform_deprecated_index.md

Warning: [Fixable] List items should be accessed using square brackets (terraform_deprecated_index)

  on outputs.tf line 22:
  22:   value       = join("", aws_acm_certificate_validation.default.*.certificate_arn)

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.5.0/docs/rules/terraform_deprecated_index.md
```
Though it's not related to your changes, linter rules seem to have been updated since the last module release.

**Comment by gberenice** [comment]
> @gberenice The pre-commit trailing-whitespace seems to interfere with the Readme. I re-ran the make readme without the pre-commit now.

Yeah, that's annoying. Thank you.

**Review by gberenice — APPROVED** [review]
LGTM 👍

**Comment by gberenice** [comment]
@joke yeah, it's supposed to be released automatically. I'm looking into that.

**Comment by gberenice** [comment]
@joke I'm discussing this with the team. Meanwhile, if this update is blocking you, the possible workaround is to reference commit SHA:
```hcl
module "acm_request_certificate" {
  source = "git::https://github.com/cloudposse/terraform-aws-acm-request-certificate.git?ref=8d052a6"

  # ... other configuration ...
}
```

**Comment by Nuru** [comment]
@joke This PR is included in the now released v0.18.0

**Pull request merged**
