### PR TITLE
Fix aws provider version for latest terraform 0.13

### PR DESCRIPTION
**Pull request by reixd**
## what
* Updated the required provider versions to get this module working with the latest terraform 0.13 release

## why
* Without this patch this module does not work with terraform 0.13.4

### CODE REVIEW

**Comment by Gowiem** [comment]
@reixd We've been just pinning the minimum version like so: 

```
terraform {
  required_version = ">= 0.12.0"

  required_providers {
    aws      = ">= 2.0"
    template = ">= 2.0"
    null     = ">= 2.0"
  }
}
```

Mind updating to that?

**Comment by reixd** [comment]
> 
> Mind updating to that?

Nope, pushed a patch with the corresponding fixes ;)

**Review by Gowiem — APPROVED** [review]

**Pull request merged**
